version: '3'
services:
  flask:
    build: TrotiNet_Webapp
    command: flask run -h 0.0.0.0
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_PORT=5001
      - FLASK_RUN_HOST="0.0.0.0"
    ports: 
      - '5001:5001'
    depends_on:
      - prometheus


  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090


  kafka:
    image: confluentinc/cp-kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper
      - prometheus


  zookeeper:
    image: confluentinc/cp-zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

